"""Week 4: head-to-head comparison of best single-drug vs best combo prediction.

This is the primary research question of the project:

    Hypothesis: For AML patients, the best-predicted drug combination beats the
    best-predicted single drug in terms of (predicted) AUC.

Methodology, per patient p:
    best_single(p) = min over d of single_drug_pred(p, d)
    best_combo(p)  = min over (d1, d2) pairs of combo_auc(p, d1, d2)
    Δ(p) = best_single(p) - best_combo(p)

A POSITIVE Δ means combo < single (lower AUC = more cell killing = better).

Primary statistic: mean(Δ) + 95% CI via bootstrap (B=2000).
Permutation test: shuffle single/combo labels within-patient; H0 rejected if
observed mean(Δ) exceeds 97.5th percentile of null distribution.

Subgroup analyses (Week 4 extension):
  - By ELN risk (Favorable / Intermediate / Adverse)
  - By FLT3-mutation status (mut_FLT3 == 1 vs 0)
  - By mechanism-prior engagement
    (patients with at least one driver-target deficit vs those without)

Outputs:
  runs/head_to_head/
    ├── per_patient_delta.csv       # pid, best_single, best_combo, delta, picks
    ├── summary.json                # overall mean/CI/p-value + subgroup stats
    └── delta_distribution.png      # histogram (generated by fig module)
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
import pandas as pd


@dataclass(frozen=True)
class HeadToHeadConfig:
    baseline_pred_path: Path = Path(
        "runs/baseline_single_drug_mlp/predictions_all_patients_all_drugs.csv"
    )
    combo_auc_npz_path: Path = Path("runs/combo_predictor/combo_auc_predictions.npz")
    patient_features_path: Path = Path("data/canonical/beataml_patient_features.csv")
    out_dir: Path = Path("runs/head_to_head")
    bootstrap_n: int = 2000
    permutation_n: int = 2000
    random_state: int = 42
    # Optional drug filter: if non-empty, restrict BOTH single and combo
    # candidates to this set. Used for clinically-relevant analysis where we
    # drop pan-cytotoxic BeatAML winners (Elesclomol, Panobinostat, Flavopiridol,
    # etc.) and keep drugs that are mechanism-annotated or AML-clinical-stage.
    drug_filter: tuple[str, ...] = ()
    filter_label: str = "all_drugs"


# ---------------------------------------------------------------------------
# Core computation
# ---------------------------------------------------------------------------


def compute_deltas(cfg: HeadToHeadConfig) -> pd.DataFrame:
    """Build the per-patient Δ table."""
    baseline = pd.read_csv(cfg.baseline_pred_path, index_col=0)
    npz = np.load(cfg.combo_auc_npz_path, allow_pickle=True)
    combo_auc = npz["combo_auc"]        # (n_p, n_d, n_d)
    patient_ids = npz["patient_ids"]
    drug_names = npz["drug_names"]

    assert len(patient_ids) == baseline.shape[0]
    assert list(drug_names) == list(baseline.columns)

    # Apply drug filter if specified
    if cfg.drug_filter:
        keep_idx = [i for i, d in enumerate(drug_names) if d in set(cfg.drug_filter)]
        if len(keep_idx) < 2:
            raise ValueError(
                f"drug_filter keeps only {len(keep_idx)} drugs; need ≥2 for combos")
        print(f"[h2h] drug filter '{cfg.filter_label}': {len(keep_idx)}/{len(drug_names)} drugs kept")
        baseline = baseline.iloc[:, keep_idx]
        combo_auc = combo_auc[:, keep_idx, :][:, :, keep_idx]
        drug_names = drug_names[keep_idx]

    # Best single: per patient, min across drugs
    single_best_idx = np.argmin(baseline.values, axis=1)
    best_single = baseline.values[np.arange(len(patient_ids)), single_best_idx]
    best_single_drug = baseline.columns[single_best_idx]

    # Best combo: per patient, upper-triangle (no self-pairs, no duplicates)
    n_d = combo_auc.shape[1]
    tri_i, tri_j = np.triu_indices(n_d, k=1)
    best_combo = np.zeros(len(patient_ids), dtype=np.float32)
    best_combo_d1 = np.empty(len(patient_ids), dtype=object)
    best_combo_d2 = np.empty(len(patient_ids), dtype=object)
    drug_arr = np.array(drug_names)
    for pi in range(len(patient_ids)):
        pair_aucs = combo_auc[pi, tri_i, tri_j]
        best_k = int(np.argmin(pair_aucs))
        best_combo[pi] = pair_aucs[best_k]
        best_combo_d1[pi] = drug_arr[tri_i[best_k]]
        best_combo_d2[pi] = drug_arr[tri_j[best_k]]

    delta = best_single - best_combo  # positive = combo wins

    df = pd.DataFrame({
        "patient_id": patient_ids,
        "best_single_auc": best_single,
        "best_single_drug": best_single_drug,
        "best_combo_auc": best_combo,
        "best_combo_d1": best_combo_d1,
        "best_combo_d2": best_combo_d2,
        "delta": delta,
    })
    return df


# ---------------------------------------------------------------------------
# Statistical tests
# ---------------------------------------------------------------------------


def bootstrap_ci(deltas: np.ndarray, n_boot: int,
                 rng: np.random.Generator, alpha: float = 0.05) -> tuple[float, float, float]:
    means = np.empty(n_boot, dtype=np.float64)
    n = len(deltas)
    for b in range(n_boot):
        idx = rng.integers(0, n, size=n)
        means[b] = deltas[idx].mean()
    return (
        float(deltas.mean()),
        float(np.quantile(means, alpha / 2)),
        float(np.quantile(means, 1 - alpha / 2)),
    )


def permutation_test_signed(deltas: np.ndarray, n_perm: int,
                             rng: np.random.Generator) -> float:
    """Two-sided sign-flip permutation test.

    H0: deltas have mean 0. Null: randomly flip signs of each element.
    Return p-value = fraction of |null_mean| ≥ |observed_mean|.
    """
    obs = abs(deltas.mean())
    n = len(deltas)
    hits = 0
    for _ in range(n_perm):
        signs = rng.choice([-1, 1], size=n)
        null_mean = abs((signs * deltas).mean())
        if null_mean >= obs:
            hits += 1
    return (hits + 1) / (n_perm + 1)


# ---------------------------------------------------------------------------
# Subgroup analysis
# ---------------------------------------------------------------------------


def subgroup_stats(delta_df: pd.DataFrame,
                    patient_features: pd.DataFrame,
                    rng: np.random.Generator,
                    n_boot: int) -> dict:
    """Report head-to-head stats by ELN risk, FLT3 status, and mech engagement."""
    out: dict = {}
    joined = delta_df.merge(
        patient_features.reset_index(), on="patient_id", how="left"
    )

    def _group_stat(sub: pd.DataFrame, label: str) -> dict:
        if sub.empty:
            return {"n": 0}
        deltas = sub["delta"].values
        mean, lo, hi = bootstrap_ci(deltas, n_boot, rng)
        return {
            "n": int(len(sub)),
            "mean_delta": round(mean, 2),
            "ci95_low": round(lo, 2),
            "ci95_high": round(hi, 2),
            "pct_positive": round(float((deltas > 0).mean()), 3),
        }

    # ELN subgroups
    eln_map = {0.0: "Favorable", 0.5: "FavorableOrIntermediate",
               1.0: "Intermediate", 1.5: "IntermediateOrAdverse",
               2.0: "Adverse"}
    out["by_eln"] = {}
    for ord_val, name in eln_map.items():
        sub = joined[joined["clin_eln_ordinal"] == ord_val]
        out["by_eln"][name] = _group_stat(sub, name)

    # FLT3 mut
    out["by_flt3"] = {
        "FLT3_mut": _group_stat(joined[joined["mut_FLT3"] == 1], "FLT3_mut"),
        "FLT3_wt":  _group_stat(joined[joined["mut_FLT3"] == 0], "FLT3_wt"),
    }

    # Mechanism-prior engagement (any driver target covered)
    mut_cols = ["mut_FLT3", "mut_IDH1", "mut_IDH2", "mut_NPM1", "mut_KMT2A"]
    has_deficit = joined[mut_cols].sum(axis=1) > 0
    out["by_mech_engagement"] = {
        "driver_present": _group_stat(joined[has_deficit], "driver_present"),
        "driver_absent":  _group_stat(joined[~has_deficit], "driver_absent"),
    }

    return out


# ---------------------------------------------------------------------------
# Pipeline entry
# ---------------------------------------------------------------------------


def run_head_to_head(cfg: HeadToHeadConfig | None = None) -> dict:
    cfg = cfg or HeadToHeadConfig()
    cfg.out_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(cfg.random_state)

    print(f"[h2h] loading …")
    delta_df = compute_deltas(cfg)
    pf = pd.read_csv(cfg.patient_features_path).set_index("patient_id")

    print(f"[h2h] {len(delta_df)} patients")
    print(f"[h2h] best_single: mean={delta_df['best_single_auc'].mean():.2f}  "
          f"median={delta_df['best_single_auc'].median():.2f}")
    print(f"[h2h] best_combo:  mean={delta_df['best_combo_auc'].mean():.2f}  "
          f"median={delta_df['best_combo_auc'].median():.2f}")
    print(f"[h2h] delta: mean={delta_df['delta'].mean():.2f}  "
          f"median={delta_df['delta'].median():.2f}  "
          f"std={delta_df['delta'].std():.2f}")

    # Save per-patient table
    delta_df.to_csv(cfg.out_dir / "per_patient_delta.csv", index=False)

    # Bootstrap + permutation on overall delta
    print(f"[h2h] bootstrap CI (n_boot={cfg.bootstrap_n}) …")
    deltas = delta_df["delta"].values.astype(np.float64)
    mean_d, lo, hi = bootstrap_ci(deltas, cfg.bootstrap_n, rng)
    print(f"[h2h] bootstrap: mean={mean_d:.2f}  95% CI = [{lo:.2f}, {hi:.2f}]")

    print(f"[h2h] permutation test (n_perm={cfg.permutation_n}) …")
    p_val = permutation_test_signed(deltas, cfg.permutation_n, rng)
    print(f"[h2h] permutation p-value: {p_val:.4f}")

    # Subgroup analysis
    print(f"[h2h] subgroup analysis …")
    sub = subgroup_stats(delta_df, pf, rng, cfg.bootstrap_n // 4)

    # Most-common picks
    combo_pair_counts = (
        delta_df.apply(lambda r: tuple(sorted([r["best_combo_d1"], r["best_combo_d2"]])), axis=1)
        .value_counts().head(10)
    )
    single_counts = delta_df["best_single_drug"].value_counts().head(10)

    summary = {
        "cfg": asdict(cfg),
        "n_patients": int(len(delta_df)),
        "best_single_auc": {
            "mean": round(float(delta_df["best_single_auc"].mean()), 2),
            "median": round(float(delta_df["best_single_auc"].median()), 2),
            "std": round(float(delta_df["best_single_auc"].std()), 2),
        },
        "best_combo_auc": {
            "mean": round(float(delta_df["best_combo_auc"].mean()), 2),
            "median": round(float(delta_df["best_combo_auc"].median()), 2),
            "std": round(float(delta_df["best_combo_auc"].std()), 2),
        },
        "delta": {
            "mean": round(float(mean_d), 2),
            "median": round(float(np.median(deltas)), 2),
            "std": round(float(deltas.std()), 2),
            "ci95_low": round(float(lo), 2),
            "ci95_high": round(float(hi), 2),
            "permutation_p": round(float(p_val), 4),
            "pct_positive": round(float((deltas > 0).mean()), 3),
        },
        "subgroups": sub,
        "top_combo_picks": [
            {"pair": f"{p[0]} + {p[1]}", "count": int(n)}
            for p, n in combo_pair_counts.items()
        ],
        "top_single_picks": [
            {"drug": str(d), "count": int(n)} for d, n in single_counts.items()
        ],
    }
    (cfg.out_dir / "summary.json").write_text(
        json.dumps(summary, indent=2, default=str), encoding="utf-8"
    )

    print(f"[h2h] DONE → {cfg.out_dir}")
    return summary


# Clinically-relevant AML drug panel for filtered head-to-head analysis.
# Selection criterion: drugs that (a) have mechanism annotation in our
# 20-drug vocab, OR (b) are FDA-approved for AML, OR (c) have completed
# Phase 2/3 AML trials. Excludes pan-cytotoxic chemistry probes (Elesclomol,
# Panobinostat, Flavopiridol, SNS-032, etc.) whose BeatAML AUC dominance is
# likely non-specific cytotoxicity rather than AML-selective efficacy.
CLINICALLY_RELEVANT_AML_DRUGS: tuple[str, ...] = (
    "Venetoclax",
    "Azacytidine",
    "Cytarabine",
    "Midostaurin",
    "Quizartinib (AC220)",
    "Gilteritinib",
    "Ivosidenib",
    "Enasidenib",
    "Sorafenib",
    "Crenolanib",
    "Dasatinib",
    "Nilotinib",
    "Imatinib",
    "Ponatinib",
    "Ruxolitinib (INCB018424)",
    "Trametinib (GSK1120212)",
    "Selumetinib (AZD6244)",
    "Alisertib (MLN8237)",
    "Pacritinib",
    "Crizotinib (PF-2341066)",
)


def run_sensitivity_analysis(cfg: HeadToHeadConfig | None = None) -> dict:
    """Run the head-to-head twice: all-drug and clinically-relevant-drug only.

    This separates two interpretations:
      - 'all_drugs': best_single dominated by pan-cytotoxic compounds; tests
        whether combo beats them.
      - 'clinically_relevant': restrict to ~20 AML-clinical-stage drugs;
        tests whether combo beats the best clinically-actionable single drug.
    """
    cfg = cfg or HeadToHeadConfig()

    # Pass 1: all drugs
    print("\n=== PASS 1: all 165 drugs ===")
    cfg_all = HeadToHeadConfig(
        baseline_pred_path=cfg.baseline_pred_path,
        combo_auc_npz_path=cfg.combo_auc_npz_path,
        patient_features_path=cfg.patient_features_path,
        out_dir=cfg.out_dir / "all_drugs",
        bootstrap_n=cfg.bootstrap_n, permutation_n=cfg.permutation_n,
        random_state=cfg.random_state,
        drug_filter=(), filter_label="all_drugs",
    )
    summary_all = run_head_to_head(cfg_all)

    # Pass 2: clinically relevant
    print("\n=== PASS 2: clinically-relevant AML drugs only ===")
    cfg_clin = HeadToHeadConfig(
        baseline_pred_path=cfg.baseline_pred_path,
        combo_auc_npz_path=cfg.combo_auc_npz_path,
        patient_features_path=cfg.patient_features_path,
        out_dir=cfg.out_dir / "clinical_drugs",
        bootstrap_n=cfg.bootstrap_n, permutation_n=cfg.permutation_n,
        random_state=cfg.random_state,
        drug_filter=CLINICALLY_RELEVANT_AML_DRUGS,
        filter_label="clinically_relevant",
    )
    summary_clin = run_head_to_head(cfg_clin)

    # Combined summary
    combined = {
        "all_drugs": {
            "n_drugs": 165,
            "delta_mean": summary_all["delta"]["mean"],
            "delta_ci": [summary_all["delta"]["ci95_low"],
                         summary_all["delta"]["ci95_high"]],
            "pct_positive": summary_all["delta"]["pct_positive"],
            "permutation_p": summary_all["delta"]["permutation_p"],
        },
        "clinically_relevant": {
            "n_drugs": summary_clin.get("n_drugs_in_scope", len(CLINICALLY_RELEVANT_AML_DRUGS)),
            "delta_mean": summary_clin["delta"]["mean"],
            "delta_ci": [summary_clin["delta"]["ci95_low"],
                         summary_clin["delta"]["ci95_high"]],
            "pct_positive": summary_clin["delta"]["pct_positive"],
            "permutation_p": summary_clin["delta"]["permutation_p"],
        },
    }
    (cfg.out_dir / "combined_summary.json").write_text(
        json.dumps(combined, indent=2, default=str), encoding="utf-8"
    )
    print(f"\n[h2h] combined summary → {cfg.out_dir / 'combined_summary.json'}")
    return combined


def main():
    import argparse
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--baseline-pred",
                     default="runs/baseline_single_drug_mlp/predictions_all_patients_all_drugs.csv")
    ap.add_argument("--combo-npz",
                     default="runs/combo_predictor/combo_auc_predictions.npz")
    ap.add_argument("--patient-features",
                     default="data/canonical/beataml_patient_features.csv")
    ap.add_argument("--out", default="runs/head_to_head")
    ap.add_argument("--bootstrap-n", type=int, default=2000)
    ap.add_argument("--permutation-n", type=int, default=2000)
    ap.add_argument("--sensitivity", action="store_true",
                     help="Run both all-drug and clinically-relevant analyses.")
    args = ap.parse_args()
    cfg = HeadToHeadConfig(
        baseline_pred_path=Path(args.baseline_pred),
        combo_auc_npz_path=Path(args.combo_npz),
        patient_features_path=Path(args.patient_features),
        out_dir=Path(args.out),
        bootstrap_n=args.bootstrap_n,
        permutation_n=args.permutation_n,
    )
    if args.sensitivity:
        run_sensitivity_analysis(cfg)
    else:
        run_head_to_head(cfg)


if __name__ == "__main__":
    main()
