"""Week 1 Day 5 — End-to-end data integration smoke test.

Runs quick sanity checks across all Week 1 canonical tables to confirm the
data layer is coherent and ready for Week 2-6 modeling.

Checks performed:
  1. All expected canonical files exist and load without error
  2. Schema compatibility:
     - BeatAML patient features + TCGA patient features share 80 columns
     - Drug response long table references only drugs in the BeatAML vocab
     - DrugComb strict pairs reference only drugs in the BeatAML vocab
  3. No-leakage checks:
     - Patient IDs are unique within each cohort
     - Drug IDs are consistent across BeatAML long + combo + baseline predictions
  4. Basic distribution sanity:
     - AUC values in BeatAML are in the expected 0-300 range (raw units)
     - Mutation features are binary 0/1
     - ELN ordinal is in {0.0, 0.5, 1.0, 1.5, 2.0}

Exit code 0 on success, non-zero on any failure. Writes a report to
docs/week1_day5_integration_report.md.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[2]
CANON = REPO_ROOT / "data" / "canonical"
RUNS = REPO_ROOT / "runs"
DOCS = REPO_ROOT / "docs"


def _report(report_lines: list[str], level: str, msg: str) -> None:
    prefix = {"ok": "✓", "warn": "!", "fail": "✗", "info": " "}[level]
    line = f"  {prefix}  {msg}"
    print(line)
    report_lines.append(line)


def check() -> tuple[bool, list[str]]:
    lines: list[str] = []
    all_ok = True
    lines.append("# Week 1 Day 5 — Integration Report")
    lines.append("")
    lines.append("Generated by `combo_val.integration_check`. Exit code 0 = all green.")
    lines.append("")

    # --- 1. Files exist ---
    lines.append("## 1. Canonical files exist")
    lines.append("")
    expected = {
        "BeatAML patient features": CANON / "beataml_patient_features.csv",
        "BeatAML drug response long": CANON / "beataml_drug_response_long.csv",
        "BeatAML feature manifest": CANON / "beataml_feature_manifest.json",
        "DrugComb strict pairs": CANON / "drugcomb_aml_pairs.csv",
        "DrugComb loose pairs": CANON / "drugcomb_aml_pairs_any_match.csv",
        "DrugComb monotherapy": CANON / "drugcomb_aml_monotherapy.csv",
        "DrugComb alignment": CANON / "drugcomb_drug_alignment.csv",
        "DrugComb manifest": CANON / "drugcomb_filter_manifest.json",
        "TCGA patient features": CANON / "tcga_laml_patient_features.csv",
        "TCGA clinical": CANON / "tcga_laml_clinical.csv",
        "TCGA manifest": CANON / "tcga_laml_manifest.json",
        "Baseline A predictions": RUNS / "baseline_single_drug_mlp" / "predictions_all_patients_all_drugs.csv",
        "Baseline A metrics": RUNS / "baseline_single_drug_mlp" / "cv_metrics.json",
    }
    for name, p in expected.items():
        if p.exists():
            _report(lines, "ok", f"{name}: {p.relative_to(REPO_ROOT)}")
        else:
            _report(lines, "fail", f"{name} MISSING at {p}")
            all_ok = False

    # --- 2. Schema compatibility ---
    lines.append("")
    lines.append("## 2. Schema compatibility")
    lines.append("")

    beat = pd.read_csv(CANON / "beataml_patient_features.csv")
    tcga = pd.read_csv(CANON / "tcga_laml_patient_features.csv")

    beat_cols = [c for c in beat.columns if c != "patient_id"]
    tcga_cols = [c for c in tcga.columns if c != "patient_id"]
    if beat_cols == tcga_cols:
        _report(lines, "ok", f"BeatAML & TCGA feature schemas match exactly ({len(beat_cols)} cols)")
    else:
        diff = set(beat_cols).symmetric_difference(set(tcga_cols))
        _report(lines, "fail", f"schema mismatch in {len(diff)} cols: {sorted(diff)[:5]}…")
        all_ok = False

    # --- 3. Drug vocab consistency ---
    lines.append("")
    lines.append("## 3. Drug vocabulary consistency")
    lines.append("")

    long_df = pd.read_csv(CANON / "beataml_drug_response_long.csv")
    beat_drugs = set(long_df["drug_id"].unique())
    _report(lines, "info", f"BeatAML drug vocab: {len(beat_drugs)} drugs")

    strict = pd.read_csv(CANON / "drugcomb_aml_pairs.csv")
    orphaned = set(strict["drug1_id"]).union(strict["drug2_id"]) - beat_drugs
    if not orphaned:
        _report(lines, "ok", f"All {strict['drug1_id'].nunique() + strict['drug2_id'].nunique()} drug mentions in strict pairs exist in BeatAML vocab")
    else:
        _report(lines, "fail", f"{len(orphaned)} orphaned drugs in strict pairs: {sorted(orphaned)[:5]}…")
        all_ok = False

    baseline_pred = pd.read_csv(RUNS / "baseline_single_drug_mlp" / "predictions_all_patients_all_drugs.csv",
                                index_col=0)
    baseline_drugs = set(baseline_pred.columns)
    if baseline_drugs == beat_drugs:
        _report(lines, "ok", f"Baseline A predictions cover all {len(beat_drugs)} BeatAML drugs")
    else:
        diff = baseline_drugs.symmetric_difference(beat_drugs)
        _report(lines, "warn", f"Baseline drug set differs by {len(diff)}: {sorted(diff)[:5]}")

    # --- 4. Patient uniqueness ---
    lines.append("")
    lines.append("## 4. Patient uniqueness")
    lines.append("")
    for name, df, key in [
        ("BeatAML", beat, "patient_id"),
        ("TCGA", tcga, "patient_id"),
        ("Baseline predictions", baseline_pred.reset_index(), baseline_pred.index.name or "patient_id"),
    ]:
        dups = df[key].duplicated().sum()
        if dups == 0:
            _report(lines, "ok", f"{name}: {len(df)} unique patient IDs")
        else:
            _report(lines, "fail", f"{name}: {dups} duplicate patient IDs")
            all_ok = False

    # --- 5. Distribution sanity ---
    lines.append("")
    lines.append("## 5. Distribution sanity")
    lines.append("")

    auc_vals = long_df["auc"].dropna()
    if (auc_vals.min() >= -50) and (auc_vals.max() <= 350):
        _report(lines, "ok", f"BeatAML AUC in [{auc_vals.min():.1f}, {auc_vals.max():.1f}] "
                f"(median {auc_vals.median():.1f}); within 0-300 raw scale")
    else:
        _report(lines, "warn", f"BeatAML AUC outliers: [{auc_vals.min():.1f}, {auc_vals.max():.1f}]")

    mut_cols = [c for c in beat.columns if c.startswith("mut_")]
    vals = beat[mut_cols].values.flatten()
    if set(np.unique(vals)) <= {0.0, 1.0}:
        _report(lines, "ok", f"BeatAML mutations binary across {len(mut_cols)} gene cols")
    else:
        _report(lines, "fail", f"BeatAML mutations not strictly binary: {np.unique(vals)[:5]}…")
        all_ok = False

    eln_vals = set(np.unique(beat["clin_eln_ordinal"].dropna().values))
    expected_eln = {0.0, 0.5, 1.0, 1.5, 2.0}
    if eln_vals <= expected_eln:
        _report(lines, "ok", f"ELN ordinal values {sorted(eln_vals)} in expected set")
    else:
        _report(lines, "warn", f"ELN ordinal has unexpected values: {eln_vals - expected_eln}")

    # --- 6. Week-3 readiness: combo predictor has data to train on ---
    lines.append("")
    lines.append("## 6. Week-3 readiness: combo predictor")
    lines.append("")
    strict_pairs = len(strict)
    n_drugs_in_strict = strict["drug1_id"].append(strict["drug2_id"]).nunique() if hasattr(strict["drug1_id"], "append") else len(set(strict["drug1_id"]) | set(strict["drug2_id"]))
    if strict_pairs >= 100:
        _report(lines, "ok", f"{strict_pairs} strict pairs on {n_drugs_in_strict} drugs — enough for small MLP")
    else:
        _report(lines, "warn", f"{strict_pairs} strict pairs may be too few for a robust residual model")

    # Synergy distribution
    s = strict["synergy_loewe"].dropna()
    if s.std() > 5.0 and s.mean() < 0:
        _report(lines, "ok", f"Synergy Loewe distribution: mean={s.mean():.2f} std={s.std():.2f} "
                             f"(skewed synergistic — good signal for combo model)")
    else:
        _report(lines, "warn", f"Synergy Loewe distribution may lack signal: mean={s.mean():.2f} std={s.std():.2f}")

    # --- 7. Week-5 readiness ---
    lines.append("")
    lines.append("## 7. Week-5 readiness: TCGA independent cohort")
    lines.append("")
    clin = pd.read_csv(CANON / "tcga_laml_clinical.csv")
    clin["os_months"] = pd.to_numeric(clin["OS_MONTHS"], errors="coerce")
    deceased_rate = clin["OS_STATUS"].astype(str).str.startswith("1").mean()
    _report(lines, "info", f"TCGA OS: {len(clin)} patients, deceased rate = {deceased_rate:.1%}, "
                           f"median OS = {clin['os_months'].median():.1f} months")
    n_mut = (tcga[mut_cols].sum(axis=1) > 0).sum()
    _report(lines, "info", f"TCGA mutation coverage: {n_mut}/{len(tcga)} patients have ≥1 driver mutation")

    lines.append("")
    lines.append("## Verdict")
    lines.append("")
    if all_ok:
        lines.append("**All critical checks PASS — Week 1 data layer is ready for Week 2+ modeling.**")
    else:
        lines.append("**Some checks FAILED — review failures above before proceeding.**")

    return all_ok, lines


def main() -> int:
    ok, report_lines = check()
    out = DOCS / "week1_day5_integration_report.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(report_lines) + "\n", encoding="utf-8")
    print(f"\n[integration] report → {out}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
